#!python

# Copyright (c) 2020 Adrian Siekierka
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from PIL import Image
import os.path, struct, sys

space_width = 3
font_width = 8
font_height = 11

im = Image.open(sys.argv[1]).convert("RGBA")
char_count = int(im.width / font_width)
char_widths = {}
char_index = {}
font_basename = os.path.splitext(os.path.basename(sys.argv[1]))[0]
font_index_path = "%s.txt" % sys.argv[1]
font_data_path = "%s.inc" % os.path.splitext(sys.argv[2])[0]

print("Building %dx%d font of %d characters" % (font_width, font_height, char_count))

i = 0
with open(font_index_path, "rb") as fp:
	byte = fp.read(1)
	while byte:
		if i < char_count:
			char_index[ord(byte)] = i
		i += 1
		byte = fp.read(1)

with open(sys.argv[2], "wb") as fp:
	for char_id in range(0, char_count):
		char_widths[char_id] = 0
		for iy in range(0, font_height):
			v = 0
			for ix in range(0, font_width):
				pxl = im.getpixel((ix + (char_id * font_width), iy))
				if pxl[0] < 128:
					v = v | (1 << ix)
					if (ix + 1) > char_widths[char_id]:
						char_widths[char_id] = ix + 1
			for ix in range(0, font_width, 8):
				fp.write(struct.pack("<B", (v >> ix) & 255))
		if char_widths[char_id] == 0:
			char_widths[char_id] = space_width

with open(font_data_path, "w") as fp:
	default_idx = char_index.get(ord('?'), 0)
	print("// auto-generated by font_pack\n#include \"%s_raw.h\"\n" % font_basename, file=fp)
	print("const u8 %s_index[%d] = {%s};" % (font_basename, 256, ", ".join(str(char_index.get(i, default_idx)) for i in range(0, 256))), file=fp)
	print("const u8 %s_widths[%d] = {%s};" % (font_basename, char_count, ", ".join(str(char_widths[i]) for i in range(0, char_count))), file=fp)
	print("\nconst Font %s = {" % font_basename, file=fp);
	print("\t.width = %d, .height = %d," % (font_width, font_height), file=fp)
	print("\t.char_index = %s_index," % font_basename, file=fp);
	print("\t.char_widths = %s_widths," % font_basename, file=fp);
	print("\t.data = %s_raw" % font_basename, file=fp);
	print("};", file=fp);
